(deftheme solarized-wombat-dark-bg
  "Created 2021-04-27.")

(custom-theme-set-variables
 'solarized-wombat-dark-bg
 '(ansi-color-names-vector ["#2f2f2e" "#ffb4ac" "#8ac6f2" "#e5c06d" "#a4b5e6" "#e5786d" "#7ec98f" "#74736f"])
 '(compilation-message-face 'default)
 '(cua-normal-cursor-color "#8d8b86")
 '(cua-read-only-cursor-color "#8ac6f2")
 '(cua-global-mark-cursor-color "#7ec98f")
 '(cua-overwrite-cursor-color "#e5c06d")
 '(term-default-fg-color "#8d8b86")
 '(term-default-bg-color "#2a2a29"))

(custom-theme-set-faces
 'solarized-wombat-dark-bg
 '(button ((t (:underline t))))
 '(cursor ((((class color) (min-colors 89)) (:foreground "#2a2a29" :background "#8d8b86" :inverse-video t))))
 '(error ((((class color) (min-colors 89)) (:foreground "#ddaa6f"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#834c98"))))
 '(header-line ((((class color) (min-colors 89)) (:inverse-video unspecified :overline nil :underline "#2f2f2e" :foreground "#8d8b86" :background "#2a2a29" :box (:line-width 2 :color "#2a2a29" :style unspecified)))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#2a2a29" :background "#e5c06d" :weight normal))))
 '(link ((((class color) (min-colors 89)) (:foreground "#e5c06d" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#e5c06d" :underline t :weight normal))))
 '(match ((((class color) (min-colors 89)) (:background "#2f2f2e" :foreground "#999891" :weight bold))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#8d8b86" :background "#2a2a29"))))
 '(region ((((class color) (min-colors 89)) (:extend t :foreground "#2a2a29" :background "#999891"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:extend t :background "#2f2f2e"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#6a6a65"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#ffb4ac"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#284b54"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#e5c06d"))))
 '(next-error ((((class color) (min-colors 89)) (:foreground "#f2b0a2" :background "#714943" :weight normal))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#7ec98f" :underline nil))))
 '(compilation-error ((((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#6a6a65" :underline nil :bold nil))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground unspecified :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:inherit compilation-error :foreground "#ffb4ac" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :weight bold))))
 '(completions-annotations ((t (:foreground "#6a6a65"))))
 '(cua-global-mark ((((class color) (min-colors 89)) (:background "#e5c06d" :foreground "#2a2a29"))))
 '(cua-rectangle ((((class color) (min-colors 89)) (:inherit region :background "#e5786d" :foreground "#2a2a29"))))
 '(cua-rectangle-noselect ((((class color) (min-colors 89)) (:inherit region :background "#2f2f2e" :foreground "#6a6a65"))))
 '(diary ((((class color) (min-colors 89)) (:foreground "#e5c06d"))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#a4b5e6" :weight normal))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#ffb4ac"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#2a2a29" :background "#a4b5e6"))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#e5c06d" :weight bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#e5786d" :weight bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#8d8b86" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#7ec98f" :weight normal :slant italic))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :underline t))))
 '(fill-column-indicator ((((class color) (min-colors 89)) :foreground "#2f2f2e" :weight semilight)))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#2a2a29" :background "#e5786d" :weight normal))))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "#ffb4ac" :background "#2a2a29" :bold t))))
 '(Man-overstrike ((((class color) (min-colors 89)) (:foreground "#a4b5e6" :weight bold))))
 '(Man-reverse ((((class color) (min-colors 89)) (:foreground "#ddaa6f"))))
 '(Man-underline ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#2f2f2e"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#6a6a65" :slant normal))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#7ec98f" :slant normal))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#a4b5e6"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#e5c06d" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#a4b5e6"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#e5c06d" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#7ec98f"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#e5c06d"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#a4b5e6"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:inherit error :weight bold))))
 '(c-annotation-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(custom-face-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#834c98" :weight normal))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#7ec98f" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "#6a6a65"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#a4b5e6" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#ffb4ac" :height 1.2))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(custom-button ((((class color) (min-colors 89)) (:background "#2f2f2e" :foreground "#999891" :box (:line-width 2 :style released-button)))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:background "#6a6a65" :foreground "#2f2f2e" :box (:line-width 2 :style released-button)))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:background "#6a6a65" :foreground "#999891" :box (:line-width 2 :style pressed-button)))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:inherit underline))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 89)) (:inherit custom-button-unraised :foreground "#e5786d"))))
 '(diff-added ((((class color) (min-colors 89)) (:background "#393f43" :foreground "#aed3ef"))))
 '(diff-changed ((t nil)))
 '(diff-removed ((((class color) (min-colors 89)) (:background "#463d3b" :foreground "#fec7be"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:background "#516472" :foreground "#bfdaee"))))
 '(diff-refine-changed ((((class color) (min-colors 89)) (:background "#585d6e" :foreground "#cad0e7"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:background "#785d5a" :foreground "#fdd1c7"))))
 '(diff-header ((t (:background "#2f2f2e"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#2a2a29" :foreground "#8d8b86" :weight bold))))
 '(diff-context ((((class color) (min-colors 89)) :foreground "#8d8b86")))
 '(diff-indicator-added ((t (:foreground "#8ac6f2"))))
 '(diff-indicator-changed ((t (:foreground "#a4b5e6"))))
 '(diff-indicator-removed ((t (:foreground "#ffb4ac"))))
 '(epa-mark ((((class color) (min-colors 89)) (:foreground "#e5786d" :weight bold))))
 '(epa-string ((((class color) (min-colors 89)) (:foreground "#834c98"))))
 '(epa-validity-disabled ((((class color) (min-colors 89)) (:inverse-video t :slant italic))))
 '(epa-validity-high ((((class color) (min-colors 89)) (:weight bold))))
 '(epa-validity-low ((((class color) (min-colors 89)) (:slant italic))))
 '(epa-validity-medium ((((class color) (min-colors 89)) (:slant italic))))
 '(flyspell-duplicate ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#e5c06d") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#e5c06d" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#ffb4ac") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#ffb4ac" :weight bold :underline t))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-1-empty))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-1-empty))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-2-empty))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-2-empty))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-3-empty))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-3-empty))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-low-empty))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-low-empty))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-1-empty))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-2-empty))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-3-empty))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-4-empty))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-5-empty))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-6-empty))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-low-empty))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:foreground "#ddaa6f"))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:foreground "#a4b5e6" :weight bold))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :weight bold))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:foreground "#8d8b86" :weight bold))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:foreground "#a4b5e6"))))
 '(gnus-summary-low-read ((t (:foreground "#8ac6f2"))))
 '(gnus-summary-low-ticked ((((class color) (min-colors 89)) (:foreground "#ddaa6f"))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:foreground "#8d8b86"))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#a4b5e6"))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:foreground "#ddaa6f"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:foreground "#8d8b86"))))
 '(gnus-summary-selected ((((class color) (min-colors 89)) (:foreground "#e5c06d" :weight bold))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:foreground "#e5c06d"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:foreground "#a4b5e6"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:foreground "#a4b5e6"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:foreground "#41434a"))))
 '(gnus-group-news-low-empty ((((class color) (min-colors 89)) (:foreground "#6a6a65"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:foreground "#999891" :weight bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:foreground "#999891" :weight bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-title-4 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#999891" :slant italic :weight bold))))
 '(info-header-node ((((class color) (min-colors 89)) (:inherit info-node))))
 '(info-header-xref ((((class color) (min-colors 89)) (:inherit info-xref))))
 '(info-index-match ((((class color) (min-colors 89)) (:inherit match))))
 '(info-menu-header ((((class color) (min-colors 89)) (:inherit variable-pitch :weight bold))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#ddaa6f"))))
 '(info-xref ((((class color) (min-colors 89)) (:inherit link))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:inherit (link-visited info-xref)))))
 '(message-cited-text-1 ((((class color) (min-colors 89)) (:foreground "#6a6a65"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#6a6a65"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#8d8b86" :weight normal))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#8d8b86" :weight normal))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#8d8b86" :weight normal))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#e5c06d" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#7ec98f" :weight normal))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#7ec98f"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#e5c06d" :weight bold))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#6a6a65" :slant italic))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#999891" :background "#2f2f2e" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#2a2a29")))))
 '(org-agenda-calendar-event ((((class color) (min-colors 89)) (:foreground "#999891"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 89)) (:foreground "#8d8b86" :slant italic))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#6a6a65" :background "#2a2a29" :weight normal :box (:line-width 2 :color "#2a2a29") :inverse-video nil :overline nil :slant normal :height 1.0))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#6a6a65" :weight unspecified :underline t :overline nil :box unspecified))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#a4b5e6" :background "#2a2a29"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#6a6a65" :slant italic))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "#6a6a65" :weight normal))))
 '(org-block ((((class color) (min-colors 89)) nil)))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:inherit org-meta-line :underline t))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:inherit org-meta-line :overline t))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#2a2a29" :foreground "#8d8b86" :box (:line-width 1 :style released-button)))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#6a6a65"))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#a4b5e6" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:weight bold :foreground "#8ac6f2"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#6a6a65"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#e5c06d"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#2a2a29"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#ddaa6f" :height 1.3))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#8ac6f2" :height 1.2))))
 '(org-level-3 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#a4b5e6" :height 1.15))))
 '(org-level-4 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#e5c06d" :height 1.1))))
 '(org-level-5 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#7ec98f"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#8ac6f2"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#ffb4ac"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#a4b5e6"))))
 '(org-link ((((class color) (min-colors 89)) (:inherit link))))
 '(org-meta-line ((((class color) (min-colors 89)) (:foreground "#6a6a65" :slant italic))))
 '(org-macro ((((class color) (min-colors 89)) (:foreground "#999891"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#834c98"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#7ec98f"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#a4b5e6" :weight normal))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#6a6a65" :weight bold))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(org-tag ((((class color) (min-colors 89)) (:weight bold))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#6a6a65"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#7ec98f" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#e5c06d" :weight normal :underline nil))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :weight normal :underline nil))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#6a6a65"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 89)) (:background "#e5c06d"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:background "#2f2f2e"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#2f2f2e" :strike-through nil :underline nil :slant normal :weight normal :inherit default))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#2f2f2e" :underline t :weight bold))))
 '(org-date-selected ((((class color) (min-colors 89)) (:foreground "#ffb4ac" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#8d8b86"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#999891" :weight bold :height 1.3))))
 '(org-drawer ((((class color) (min-colors 89)) (:foreground "#7ec98f"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:inherit mode-line :background "#ffb4ac"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#ddaa6f" :height 1.3))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#8ac6f2" :height 1.2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#a4b5e6" :height 1.15))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#e5c06d" :height 1.1))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#7ec98f"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#8ac6f2"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#ffb4ac"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#a4b5e6"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#e5786d" :background unspecified :weight bold))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#2f2f2e" :background "#ffb4ac" :weight bold))))
 '(term ((t (:background "#2a2a29" :foreground "#8d8b86"))))
 '(term-color-black ((t (:foreground "#2f2f2e" :background "#2f2f2e"))))
 '(term-color-red ((t (:foreground "#ffb4ac" :background "#ffb4ac"))))
 '(term-color-green ((t (:foreground "#8ac6f2" :background "#8ac6f2"))))
 '(term-color-yellow ((t (:foreground "#e5c06d" :background "#e5c06d"))))
 '(term-color-blue ((t (:foreground "#a4b5e6" :background "#a4b5e6"))))
 '(term-color-magenta ((t (:foreground "#e5786d" :background "#e5786d"))))
 '(term-color-cyan ((t (:foreground "#7ec98f" :background "#7ec98f"))))
 '(term-color-white ((t (:foreground "#e8e5db" :background "#e8e5db"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#433e33" :foreground "#eccf92" :inherit variable-pitch))))
 '(woman-bold ((((class color) (min-colors 89)) (:inherit Man-overstrike))))
 '(woman-italic ((((class color) (min-colors 89)) (:inherit Man-underline))))
 '(highlight ((((class color) (min-colors 89)) (:background "#834c98"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#a4b5e6"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#74736f"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#e8e5db" :background "#444442"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#74736f" :background "#252524"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#f6f3e8" :weight bold))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#999891"))))
 '(default ((t (:background "#121212" :foreground "#d4d2c8")))))

(provide-theme 'solarized-wombat-dark-bg)
