#!/bin/sh

userresources="$XDG_CONFIG_HOME"/X11/Xresources
usermodmap="$XDG_CONFIG_HOME"/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[[ -f "$sysresources" ]] && xrdb -merge $sysresources
[[ -f "$userresources" ]] && xrdb -merge "$userresources"
[[ -f "$sysmodmap" ]] && xmodmap $sysmodmap
[[ -f "$usermodmap" ]] && xmodmap "$usermodmap"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap -layout it
setxkbmap -option caps:swapescape

xautolock -time 30 -locker "systemctl suspend" -detectsleep &

alsactl restore
nitrogen --restore

dwmblocks &
while : ; do
    dwm >/dev/null 2>&1

done
