alias ls="ls --color=auto"
alias ll="ls -lhX"
alias la="ls -AlhLX"
alias cd="cd -P"
alias cp="cp -r"
alias mv="mv -i"
alias rm="rm -ir"
alias mkdir="mkdir -p"
alias grep="grep --color=auto"

# others
alias z="zathura"
alias vi="vim"
alias rsync="rsync --progress"
alias verible-format="verible-verilog-format --inplace --port_declarations_alignment align --"
alias verible-lint="verible-verilog-lint --"
alias tlmgr="tllocalmgr"
